- id: https://doi.org/10.1177/0956797615571017
  image: https://upload.wikimedia.org/wikipedia/en/a/aa/Psychological_Science_cover.jpg

- id: https://doi.org/10.1037/str0000137
  image: images/spire.png

- id: https://doi.org/10.1037/emo0000379
  image: https://www.apa.org/pubs/journals/images/emo-150.gif

- id: https://doi.org/10.3389/fpsyg.2019.02962
  image: images/NavyBUDs.png

- id: https://doi.org/10.1177/2515245917740427
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2

- id: https://doi.org/10.1111/josi.12417
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg

- id: https://doi.org/10.1126/science.ade4420

- id: https://doi.org/10.1007/s10648-022-09715-z

- id: https://doi.org/10.1037/xge0001396

- id: https://doi.org/10.1167/11.11.114

# - id: https://psycnet.apa.org/record/2020-23031-009