- id: https://doi.org/10.1177/0956797615571017
  image: https://upload.wikimedia.org/wikipedia/en/a/aa/Psychological_Science_cover.jpg

- id: https://doi.org/10.1037/str0000137
  image: images/spire.png

- id: https://doi.org/10.1037/emo0000379
  image: https://www.apa.org/pubs/journals/images/emo-150.gif

- id: https://doi.org/10.3389/fpsyg.2019.02962
  image: images/NavyBUDs.png

- id: https://doi.org/10.1177/2515245917740427
  image: images/ammps.png

- id: https://doi.org/10.1111/josi.12417
  image: https://spssi.onlinelibrary.wiley.com/cms/asset/83a9fc34-7066-4e1e-86b7-20d3ba797c82/josi.12594.fp.png

- id: https://doi.org/10.1126/science.ade4420
  image: https://www.science.org/cms/asset/ec4d83c2-108e-4fd0-8316-d915987de1ab/science.2023.380.issue-6644.largecover.jpg

- id: https://doi.org/10.1007/s10648-022-09715-z
  image: https://media.springernature.com/full/springer-static/cover-hires/journal/10648

- id: https://doi.org/10.1037/xge0001396
  title: 'Evaluation of the Rethink Stress Mindset Intervention: A Metacognitive Approach to Changing Mindsets'
  authors:
  - Alia J. Crum
  - Erik Santoro
  - Isaac Handley-Miner
  - Eric N. Smith
  - Kris Evans
  - Neema Moraveji
  - Shawn Achor
  - Peter Salovey
  publisher: 'Journal of Experimental Psychology: General'
  date: '2023-05-18'
  link: https://doi.org/10.1037/xge0001396
  image: https://www.apa.org/pubs/journals/images/xge-150.gif

- id: https://psycnet.apa.org/record/2020-23031-009
  title: 'The stress‑mindset intervention. In G. M. Walton & A. J. Crum (Eds.), Handbook of wise interventions: How social psychology can help people change.'
  authors:
  - Alia J. Crum
  - Isaac J. Handley-Miner
  - Eric N. Smith
  publisher: The Guilford Press
  date: '2022-10-04'
  link: https://www.guilford.com/books/Handbook-of-Wise-Interventions/Walton-Crum/9781462551002
  image: https://www.guilford.com/covers/large/9781462551002.jpg


- id: https://doi.org/10.26300/es6b-sm82
  publisher: EdWorkingPaper
  date: '2023-09-01'
  image: images/chatbot_message.png